### ISSUE TITLE
Fail to parse this file - No #NEXUS token found.

### ISSUE THREAD

**Issue by SimonGreenhill** [dlce-eva/commonnexus#17]
```python

Traceback (most recent call last):
  File "/Users/simon/projects/phlorest/data/./venv/bin/commonnexus", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/simon/projects/phlorest/data/venv/lib/python3.11/site-packages/commonnexus/__main__.py", line 96, in main
    args = parsed_args or parser.parse_args(args=args)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 1862, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 1895, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 2110, in _parse_known_args
    stop_index = consume_positionals(start_index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 2066, in consume_positionals
    take_action(action, args)
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 1971, in take_action
    action(self, namespace, argument_values, option_string)
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 1234, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 1895, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 2110, in _parse_known_args
    stop_index = consume_positionals(start_index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 2066, in consume_positionals
    take_action(action, args)
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 1955, in take_action
    argument_values = self._get_values(action, argument_strings)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 2489, in _get_values
    value = self._get_value(action, arg_string)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/.pyenv/versions/3.11.1/lib/python3.11/argparse.py", line 2522, in _get_value
    result = type_func(arg_string)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simon/projects/phlorest/data/venv/lib/python3.11/site-packages/commonnexus/cli_util.py", line 45, in __call__
    return Nexus(string)
           ^^^^^^^^^^^^^
  File "/Users/simon/projects/phlorest/data/venv/lib/python3.11/site-packages/commonnexus/nexus.py", line 117, in __init__
    assert token.type == TokenType.WORD and token.text.upper() == NEXUS, \
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: No #NEXUS token found.
```

File: 
```
#NEXUS

Begin taxa;
	Dimensions ntax=4;
	Taxlabels
		"Chinese SL"
		"Hong Kong SL"
		"Japanese SL"
		"Taiwanese SL"
		;
End;

Begin trees;
	Translate
		1 "Chinese SL",
		2 "Hong Kong SL",
		3 "Japanese SL",
		4 "Taiwanese SL"
		;
tree TREE1 = [&R] ((3[&length_range={60.05225888,84.99131487},height_95%_HPD={0.0,4.000000330961484E-8},length_95%_HPD={62.69438897,84.99131487},length=75.15150609091343,length_median=75.96495743,height_median=0.0,height_range={0.0,9.999999406318238E-8},height=7.477401036718827E-9]:75.15150609,4[&length_range={60.05225888,84.99131487},height_95%_HPD={0.0,4.000000330961484E-8},length_95%_HPD={62.69438897,84.99131487},length=75.15150609091343,length_median=75.96495743,height_median=0.0,height_range={0.0,9.999999406318238E-8},height=7.477401036718827E-9]:75.15150609)[&length_range={15.41080891,168.2252254},height_95%_HPD={62.694388970000006,84.99131486999998},length_95%_HPD={27.39603655,126.5958814},length=77.78244698406658,posterior=1.0,length_median=76.656692185,height_median=75.96495744500001,height_range={60.05225888000001,84.99131486999998},height=75.15150609839081]:77.78244698,(1[&length_range={45.28227885,228.115424},height_95%_HPD={0.0,4.000003173132427E-8},length_95%_HPD={55.39253864,147.9157189},length=99.66217523096665,length_median=97.706314205,height_median=0.0,height_range={0.0,9.000001455206075E-8},height=8.20400129934266E-9]:99.66217523,2[&length_range={45.28227885,228.115424},height_95%_HPD={0.0,4.000003173132427E-8},length_95%_HPD={56.43794469,148.3359581},length=99.60662793709997,length_median=97.706314205,height_median=0.0,height_range={0.0,9.000001455206075E-8},height=8.25466789441028E-9]:99.60662794)[&length_range={0.6549981681,148.0118036},height_95%_HPD={57.18353745,148.16002181},length_95%_HPD={12.41789828,94.41563194},length=53.76596471182186,posterior=0.992,length_median=52.11296762,height_median=97.32151432500001,height_range={45.28227885,228.115424},height=99.31492745194575]:53.33583699)[&height_95%_HPD={104.56349859,203.34560872},length=0.0,posterior=1.0,height_median=151.60587039499998,height_range={86.98625668,251.72411834000002},height=153.00652409032273];
End;
```

**Comment by xrotwang** [comment]
Hm. Can't reproduce:
```python
>>> res = Nexus.from_file('test2.nex')
>>> import pathlib
>>> res = Nexus(pathlib.Path('test2.nex').read_text(encoding='utf8'))
```

**Comment by SimonGreenhill** [comment]
My fault -- I was running `commonnexus trees describe filename` rather than `--describe` by mistake
